"""empty message

Revision ID: 693be0477633
Revises: 957fb898a759
Create Date: 2019-09-11 16:59:56.587163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693be0477633'
down_revision = '957fb898a759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('company_no', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'company_no')
    # ### end Alembic commands ###
